version: '3'
services:

    #PHP Service
    app:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        volumes:
            - ./:/var/www
        container_name: wb_app
        depends_on:
            - mysql

    #MySQL Service
    mysql:
        image: mysql:8.0
        container_name: wb_db
        restart: always
        volumes:
            - ./tmp/db/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: wb_api_database
        ports:
            - "8111:8111"
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --port=8111
